openapi: 3.0.2
info:
  description: Ratenkauf Verkauf-V3 API for ratenkauf App
  title: Ratenkauf Verkauf-V3 API Definition
  version: V3.68.3
servers:
- url: /
tags:
- description: endpoints for operations regarding a webshop
  name: webshop
- description: |-
    ' -- endpoints used to process a transaction --
    -- BODY SIGNATURE -- All Transaction endpoints support body signature. If this feature is activated (in your self-service-portal), you need to send a signature header with name "Content-signature". Please use the following: sha256={ Sha256( yourJsonBody + signatureSecret ) } example: Content-signature: sha256=02ad96c7e912936939f2d7a25ca67e20a2b464c8737a2f3a9ccb46635e4a9f02 Please note that you need to normalize the body, i.e. remove all newlines "\n", carriage returns "\r" and tabulator spaces "\t". If you do not send a signature or if signature validation fails -> HTTP 400. The signature response from our service is in the same format. '
  name: transaction
paths:
  /api/payment/v3/webshop/integrationcheck:
    post:
      description: ''' After integrating the authentication credentials (basic auth:
        webshop id/ratenkauf token) and possibly enabling the body signature feature,
        the merchant can check its correctness. '''
      requestBody:
        $ref: '#/components/requestBodies/IntegrationCheckRequest'
      responses:
        200:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/IntegrationCheckResponse'
          description: The authentication credentials and, if enabled, the body signature
            are valid
        400:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request is invalid and has one or more constraint violations.
        401:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
          description: The request has not been applied because it lacks valid authentication
            credentials.
        403:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request could not be completed due to permanent denial
            of access to a resource or entity.
      security:
      - basicAuth: []
      summary: Verifies the correctness of the merchant's authentication credentials
        and, if enabled, the body signature
      tags:
      - webshop
  /api/payment/v3/webshop:
    get:
      description: ''' This API returns the necessary information of the corresponding
        webshop. This includes max and min financing amount, interest rate, test mode
        and current availability information '''
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebshopResponse'
          description: Ratenkauf information about a webshop
        401:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
          description: The request has not been applied because it lacks valid authentication
            credentials.
        403:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request could not be completed due to permanent denial
            of access to a resource or entity.
      security:
      - basicAuth: []
      summary: Get the necessary information about the webshop
      tags:
      - webshop
  /api/payment/v3/transaction:
    post:
      description: ''' A transaction is created with unique identifiers (a TeamBank
        identifier <technicalTransactionId> and a functional identifier <transactionId>).
        The data in the request is validated and normalised and, if necessary, corresponding
        error messages are returned. Supports body signature. '''
      requestBody:
        $ref: '#/components/requestBodies/TransactionInitRequest'
      responses:
        201:
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/TransactionInitResponse'
          description: Transaction data
        400:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request is invalid and has one or more constraint violations.
        401:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
          description: The request has not been applied because it lacks valid authentication
            credentials.
        403:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request could not be completed due to permanent denial
            of access to a resource or entity.
      security:
      - basicAuth: []
      summary: Initiates a transaction based on the given request
      tags:
      - transaction
  /api/payment/v3/transaction/{technicalTransactionId}:
    patch:
      description: Based on the unique TeamBank identifier, transaction's specific
        data is modified. Supports body signature.
      parameters:
      - description: Unique TeamBank transaction identifier
        explode: false
        in: path
        name: technicalTransactionId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/TransactionUpdateRequest'
      responses:
        200:
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/TransactionSummaryResponse'
          description: Transaction updated data
        400:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request is invalid and has one or more constraint violations.
        401:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
          description: The request has not been applied because it lacks valid authentication
            credentials.
        403:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request could not be completed due to permanent denial
            of access to a resource or entity.
        404:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request could not be completed due to an entity that was
            not found.
      security:
      - basicAuth: []
      summary: Updates a transaction based on the given request
      tags:
      - transaction
  /api/payment/v3/transaction/{technicalTransactionId}/summary:
    get:
      description: ''' Based on the unique TeamBank identifier, the necessary information
        of the corresponding transaction is returned for checkout. Supports body signature.
        '''
      parameters:
      - description: Unique TeamBank transaction identifier
        explode: false
        in: path
        name: technicalTransactionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/TransactionSummaryResponse'
          description: Transaction summary data for checkout
        400:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request is invalid and has one or more constraint violations.
        401:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
          description: The request has not been applied because it lacks valid authentication
            credentials.
        403:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request could not be completed due to permanent denial
            of access to a resource or entity.
        404:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request could not be completed due to an entity that was
            not found.
      security:
      - basicAuth: []
      summary: Get the necessary information regarding the transaction for checkout
      tags:
      - transaction
  /api/payment/v3/transaction/{technicalTransactionId}/authorization:
    get:
      description: ''' The authorization status of a transaction will be returned.
        '''
      parameters:
      - description: Unique TeamBank transaction identifier
        explode: false
        in: path
        name: technicalTransactionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/AuthorizationStatusResponse'
          description: Status of an authorization
        400:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request is invalid and has one or more constraint violations.
        401:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
          description: The request has not been applied because it lacks valid authentication
            credentials.
        404:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request could not be completed due to an entity that was
            not found.
      security:
      - basicAuth: []
      summary: Returns the authorization status of a transaction
      tags:
      - transaction
  /api/payment/v3/transaction/{technicalTransactionId}/preAuthorization:
    post:
      description: ''' The preauthorization of a transaction will be triggered asynchronous.
        After processing all necessary checks there will be an optional callback to
        the url that was provided in initialization and you can get the updated status
        information. '''
      parameters:
      - description: Unique TeamBank transaction identifier
        explode: false
        in: path
        name: technicalTransactionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        202:
          description: accepted for processing
        400:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request is invalid and has one or more constraint violations.
        401:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AuthenticationError'
          description: The request has not been applied because it lacks valid authentication
            credentials.
        403:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ConstraintViolation'
          description: The request could not be completed due to permanent denial
            of access to a resource or entity.
      security:
      - basicAuth: []
      summary: Preauthorizes a transaction after finishing the process in a webshop
      tags:
      - transaction
components:
  parameters:
    technicalTransactionId:
      description: Unique TeamBank transaction identifier
      explode: false
      in: path
      name: technicalTransactionId
      required: true
      schema:
        type: string
      style: simple
  requestBodies:
    IntegrationCheckRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IntegrationCheckRequest'
      description: integration check request
    TransactionInitRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TransactionInitRequest'
      description: init request
    TransactionUpdateRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TransactionUpdateRequest'
      description: update request
  responses:
    default:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ServerError'
      description: Internal server error or error from third party services
    IntegrationCheckResponse:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/IntegrationCheckResponse'
      description: The authentication credentials and, if enabled, the body signature
        are valid
    AuthorizationStatusResponse:
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/AuthorizationStatusResponse'
      description: Status of an authorization
    WebshopResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WebshopResponse'
      description: Ratenkauf information about a webshop
    TransactionInitResponse:
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/TransactionInitResponse'
      description: Transaction data
    TransactionUpdateResponse:
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/TransactionSummaryResponse'
      description: Transaction updated data
    TransactionSummaryResponse:
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/TransactionSummaryResponse'
      description: Transaction summary data for checkout
    ConstraintViolationError:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ConstraintViolation'
      description: The request is invalid and has one or more constraint violations.
    AuthenticationError:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/AuthenticationError'
      description: The request has not been applied because it lacks valid authentication
        credentials.
    ForbiddenError:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ConstraintViolation'
      description: The request could not be completed due to permanent denial of access
        to a resource or entity.
    NotFoundError:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ConstraintViolation'
      description: The request could not be completed due to an entity that was not
        found.
  schemas:
    IntegrationCheckRequest:
      example:
        message: ratenkauf by easyCredit
      properties:
        message:
          description: For a valid request, the value can be any string but cannot
            be empty
          example: ratenkauf by easyCredit
          type: string
      required:
      - message
      type: object
    TransactionInitRequest:
      example:
        orderDetails:
          orderId: A1ZU560
          numberOfProductsInShoppingCart: 2
          invoiceAddress:
            zip: "90471"
            country: DE
            address: Beuthener Str. 25
            city: Nürnberg
            additionalAddressInformation: 3 OG
          shoppingCartInformation:
          - quantity: 1
            articleNumber:
            - number: "1111111"
              numberType: GTIN
            - number: "1111111"
              numberType: GTIN
            price: 599.95
            productName: Washing Machine
            manufacturer: Siemens
            productCategory: Household Appliances
          - quantity: 1
            articleNumber:
            - number: "1111111"
              numberType: GTIN
            - number: "1111111"
              numberType: GTIN
            price: 599.95
            productName: Washing Machine
            manufacturer: Siemens
            productCategory: Household Appliances
          orderValue: 2614.79
        redirectLinks:
          urlSuccess: https://www.poolpowershop.de/payment_easycredit/return
          urlPreAuthorizationCallback: urlPreAuthorizationCallback
          urlDenial: https://zoolatino.de/module/easycreditratenkauf/denied
          urlCancellation: https://zoolatino.de/module/easycreditratenkauf/canceled
        shopsystem:
          shopSystemModuleVersion: 1.6.3
          shopSystemManufacturer: Shopware 5.5.10
        customerRelationship:
          customerStatus: NEW_CUSTOMER
          customerSince: 2007-10-10T00:00:00.000+0000
          orderDoneWithLogin: false
          riskyItemsInShoppingCart: false
          logisticsServiceProvider: Hermes
          numberOfOrders: 3
          negativePaymentInformation: NO_PAYMENT_DISRUPTION
        financingTerm: 6
        customer:
          firstName: Max
          lastName: Müller
          birthPlace: birthPlace
          bank:
            iban: DE123456789012345678909
          gender: MR
          contact:
            mobilePhoneNumber: "17186397426"
            skipMobilePhoneNumberCheck: false
            phoneNumber: phoneNumber
            email: test@test.de
          employment:
            monthlyNetIncome: 3000
            employmentType: EMPLOYEE
          title: PROFDR
          birthDate: 1949-10-17
          birthName: birthName
      properties:
        financingTerm:
          description: ''' Duration in months, depending on individual shop conditions
            and order value (please check your ratenkauf widget). Will be set to default
            value if not available. '''
          example: 6
          type: integer
        orderDetails:
          $ref: '#/components/schemas/OrderDetails'
        shopsystem:
          $ref: '#/components/schemas/Shopsystem'
        customer:
          $ref: '#/components/schemas/Customer'
        customerRelationship:
          $ref: '#/components/schemas/CustomerRelationship'
        redirectLinks:
          $ref: '#/components/schemas/RedirectLinks'
      required:
      - customer
      - orderDetails
      - redirectLinks
      - shopIdentifier
      type: object
    TransactionUpdateRequest:
      example:
        numberOfProductsInShoppingCart: 2
        shoppingCartInformation:
        - quantity: 1
          articleNumber:
          - number: "1111111"
            numberType: GTIN
          - number: "1111111"
            numberType: GTIN
          price: 599.95
          productName: Washing Machine
          manufacturer: Siemens
          productCategory: Household Appliances
        - quantity: 1
          articleNumber:
          - number: "1111111"
            numberType: GTIN
          - number: "1111111"
            numberType: GTIN
          price: 599.95
          productName: Washing Machine
          manufacturer: Siemens
          productCategory: Household Appliances
        orderValue: 2614.79
      properties:
        orderValue:
          description: Amount in €
          example: 2614.79
          maximum: 10000
          minimum: 199
          type: number
        numberOfProductsInShoppingCart:
          example: 2
          type: integer
        shoppingCartInformation:
          items:
            $ref: '#/components/schemas/ShoppingCartInformationItem'
          minItems: 1
          type: array
      required:
      - orderValue
      type: object
    Shopsystem:
      description: technischeShopparameter
      example:
        shopSystemModuleVersion: 1.6.3
        shopSystemManufacturer: Shopware 5.5.10
      properties:
        shopSystemManufacturer:
          description: Shop system manufacturer
          example: Shopware 5.5.10
          type: string
        shopSystemModuleVersion:
          description: Shop system module version
          example: 1.6.3
          type: string
      type: object
    OrderDetails:
      example:
        orderId: A1ZU560
        numberOfProductsInShoppingCart: 2
        invoiceAddress:
          zip: "90471"
          country: DE
          address: Beuthener Str. 25
          city: Nürnberg
          additionalAddressInformation: 3 OG
        shoppingCartInformation:
        - quantity: 1
          articleNumber:
          - number: "1111111"
            numberType: GTIN
          - number: "1111111"
            numberType: GTIN
          price: 599.95
          productName: Washing Machine
          manufacturer: Siemens
          productCategory: Household Appliances
        - quantity: 1
          articleNumber:
          - number: "1111111"
            numberType: GTIN
          - number: "1111111"
            numberType: GTIN
          price: 599.95
          productName: Washing Machine
          manufacturer: Siemens
          productCategory: Household Appliances
        orderValue: 2614.79
      properties:
        orderValue:
          description: Amount in €
          example: 2614.79
          type: number
        orderId:
          description: Shop transaction identifier (allows the shop to store its own
            reference for the transaction)
          example: A1ZU560
          maxLength: 50
          pattern: '[a-zA-Z0-9\.:\-_/]*'
          type: string
        numberOfProductsInShoppingCart:
          description: anzahlProdukteImWarenkorb
          example: 2
          type: integer
        invoiceAddress:
          $ref: '#/components/schemas/Address'
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress'
        shoppingCartInformation:
          items:
            $ref: '#/components/schemas/ShoppingCartInformationItem'
          minItems: 1
          type: array
      required:
      - invoiceAddress
      - orderValue
      - shippingAddress
      type: object
    Customer:
      example:
        firstName: Max
        lastName: Müller
        birthPlace: birthPlace
        bank:
          iban: DE123456789012345678909
        gender: MR
        contact:
          mobilePhoneNumber: "17186397426"
          skipMobilePhoneNumberCheck: false
          phoneNumber: phoneNumber
          email: test@test.de
        employment:
          monthlyNetIncome: 3000
          employmentType: EMPLOYEE
        title: PROFDR
        birthDate: 1949-10-17
        birthName: birthName
      properties:
        gender:
          description: MR = HERR, MRS = FRAU, DIVERS = DIVERS, NO_GENDER = OHNE
          enum:
          - MR
          - MRS
          - DIVERS
          - NO_GENDER
          type: string
        firstName:
          example: Max
          maxLength: 27
          minLength: 2
          pattern: '[-a-zA-ZäüößÄÖÜ\.\, ]*'
          type: string
        lastName:
          example: Müller
          maxLength: 27
          minLength: 2
          pattern: '[-a-zA-ZäüößÄÖÜ\.\, ]*'
          type: string
        birthDate:
          example: 1949-10-17
          type: string
        birthName:
          description: Buyer birth name
          maxLength: 27
          minLength: 2
          pattern: '[-a-zA-ZäüößÄÖÜ\.\, ]*'
          type: string
        birthPlace:
          description: Buyer birth place
          type: string
        title:
          enum:
          - PROFDR
          - DR
          - PROF
          - DRDR
          type: string
        contact:
          $ref: '#/components/schemas/Contact'
        bank:
          $ref: '#/components/schemas/Bank'
        employment:
          $ref: '#/components/schemas/Employment'
      required:
      - contact
      - firstName
      - lastName
      type: object
    Employment:
      example:
        monthlyNetIncome: 3000
        employmentType: EMPLOYEE
      properties:
        employmentType:
          description: EMPLOYEE = ANGESTELLTER, EMPLOYEE_PUBLIC_SECTOR = ANGESTELLTER_OEFFENTLICHER_DIENST,
            WORKER = ARBEITER, CIVIL_SERVANT = BEAMTER, RETIREE = RENTNER, SELF_EMPLOYED
            = SELBSTAENDIGER, UNEMPLOYED = ARBEITSLOSER, OTHER = SONSTIGES
          enum:
          - EMPLOYEE
          - EMPLOYEE_PUBLIC_SECTOR
          - WORKER
          - CIVIL_SERVANT
          - RETIREE
          - SELF_EMPLOYED
          - UNEMPLOYED
          - OTHER
          type: string
        monthlyNetIncome:
          description: Income in €
          example: 3000
          type: number
      type: object
    Address:
      example:
        zip: "90471"
        country: DE
        address: Beuthener Str. 25
        city: Nürnberg
        additionalAddressInformation: 3 OG
      properties:
        address:
          description: Street and street number
          example: Beuthener Str. 25
          type: string
        additionalAddressInformation:
          example: 3 OG
          maxLength: 50
          type: string
        zip:
          description: Postal code
          example: "90471"
          type: string
        city:
          example: Nürnberg
          type: string
        country:
          description: Country as 2-digit ISO code
          example: DE
          type: string
      required:
      - address
      - city
      - country
      - zip
      type: object
    ShippingAddress:
      allOf:
      - $ref: '#/components/schemas/Address'
      - $ref: '#/components/schemas/ShippingAddress_allOf'
    Contact:
      example:
        mobilePhoneNumber: "17186397426"
        skipMobilePhoneNumberCheck: false
        phoneNumber: phoneNumber
        email: test@test.de
      properties:
        email:
          example: test@test.de
          maxLength: 80
          type: string
        mobilePhoneNumber:
          description: Required in Ratenkauf process. Can be added later if not presented
            when initializing.
          example: "17186397426"
          type: string
        skipMobilePhoneNumberCheck:
          description: true if the field mobile phone number should not be checked
          example: false
          type: boolean
        phoneNumber:
          description: Customer phone number.
          type: string
      required:
      - email
      type: object
    Bank:
      description: International Bank Account Number
      example:
        iban: DE123456789012345678909
      properties:
        iban:
          example: DE123456789012345678909
          type: string
      type: object
    CustomerRelationship:
      description: Risk relevant information
      example:
        customerStatus: NEW_CUSTOMER
        customerSince: 2007-10-10T00:00:00.000+0000
        orderDoneWithLogin: false
        riskyItemsInShoppingCart: false
        logisticsServiceProvider: Hermes
        numberOfOrders: 3
        negativePaymentInformation: NO_PAYMENT_DISRUPTION
      properties:
        customerStatus:
          description: NEW_CUSTOMER = NEUKUNDE, EXISTING_CUSTOMER = BESTANDSKUNDE,
            PREMIUM_CUSTOMER = PREMIUMKUNDE
          enum:
          - NEW_CUSTOMER
          - EXISTING_CUSTOMER
          - PREMIUM_CUSTOMER
          type: string
        customerSince:
          example: 2007-10-10
          format: date
          type: string
        orderDoneWithLogin:
          description: true if the order was placed via customer login
          example: false
          type: boolean
        numberOfOrders:
          example: 3
          type: integer
        negativePaymentInformation:
          description: Indicates whether the customer has already been in late payment
            or has not made the payment -> NO_PAYMENT_DISRUPTION = KEINE_ZAHLUNGSSTOERUNGEN,
            PAYMENT_DELAY = ZAHLUNGSVERZOEGERUNG, PAYMENT_NOT_DONE = ZAHLUNGSAUSFALL,
            NO_INFORMATION = KEINE_INFORMATION
          enum:
          - NO_PAYMENT_DISRUPTION
          - PAYMENT_DELAY
          - PAYMENT_NOT_DONE
          - NO_INFORMATION
          type: string
        riskyItemsInShoppingCart:
          description: risikoartikelImWarenkorb
          example: false
          type: boolean
        logisticsServiceProvider:
          description: Logistics service provider for the delivery of the order
          example: Hermes
          type: string
      required:
      - orderDoneWithLogin
      type: object
    RedirectLinks:
      description: Redirect url addresses in case of success, cancellation and denial
      example:
        urlSuccess: https://www.poolpowershop.de/payment_easycredit/return
        urlPreAuthorizationCallback: urlPreAuthorizationCallback
        urlDenial: https://zoolatino.de/module/easycreditratenkauf/denied
        urlCancellation: https://zoolatino.de/module/easycreditratenkauf/canceled
      properties:
        urlSuccess:
          description: urlErfolg -> Return url address if the transaction is successful
          example: https://www.poolpowershop.de/payment_easycredit/return
          type: string
        urlCancellation:
          description: urlAbbruch -> Return url address if the transaction is canceled
          example: https://zoolatino.de/module/easycreditratenkauf/canceled
          type: string
        urlDenial:
          description: urlAblehnung -> Return url address if the transaction is denied
          example: https://zoolatino.de/module/easycreditratenkauf/denied
          type: string
        urlPreAuthorizationCallback:
          description: ''' Optional Callback-Url for preAuthorization endpoint. If
            provided the callback will be performed, else not. '''
          type: string
      required:
      - urlCancellation
      - urlDenial
      - urlSuccess
      type: object
    ShoppingCartInformation:
      items:
        $ref: '#/components/schemas/ShoppingCartInformationItem'
      minItems: 1
      type: array
    ShoppingCartInformationItem:
      example:
        quantity: 1
        articleNumber:
        - number: "1111111"
          numberType: GTIN
        - number: "1111111"
          numberType: GTIN
        price: 599.95
        productName: Washing Machine
        manufacturer: Siemens
        productCategory: Household Appliances
      properties:
        productName:
          example: Washing Machine
          type: string
        quantity:
          example: 1
          type: integer
        price:
          description: Amount in €
          example: 599.95
          type: number
        manufacturer:
          example: Siemens
          type: string
        productCategory:
          example: Household Appliances
          type: string
        articleNumber:
          description: Article number of a product
          items:
            $ref: '#/components/schemas/ArticleNumberItem'
          type: array
      required:
      - price
      - productName
      - quantity
      type: object
    ArticleNumberItem:
      example:
        number: "1111111"
        numberType: GTIN
      properties:
        numberType:
          description: Number type of the article
          example: GTIN
          type: string
        number:
          description: Article number of the given type
          example: "1111111"
          type: string
      required:
      - number
      - numberType
      type: object
    IntegrationCheckResponse:
      properties:
        message:
          description: Same message that was sent in the corresponding request
          example: ratenkauf by easyCredit
          type: string
      type: object
    WebshopResponse:
      example:
        interestRate: 8.5
        minFinancingAmount: 200
        maxFinancingAmount: 10000
        testMode: false
        availability: true
      properties:
        maxFinancingAmount:
          example: 10000
          type: integer
        minFinancingAmount:
          example: 200
          type: integer
        interestRate:
          example: 8.5
          type: number
        availability:
          description: true if financing is available from this webshop
          example: true
          type: boolean
        testMode:
          description: true if the webshop is in test mode
          example: false
          type: boolean
      type: object
    TransactionInitResponse:
      properties:
        technicalTransactionId:
          description: Unique TeamBank transaction identifier
          example: 1.de.4145.1-0303135329-211
          type: string
        transactionId:
          description: Unique functional transaction identifier (consists of 6 characters)
          example: EWZEN7
          type: string
        deviceIdentToken:
          description: Verification token to identify the device
          example: bd982c1b-f830-4ebc-9cfd-6ca28c17adeb
          type: string
        timestamp:
          example: 2021-03-04T14:41:09.002Z
          format: date-time
          type: string
      type: object
    TransactionSummaryResponse:
      properties:
        orderValue:
          description: Amount of the order value in € ( = Bestellwert in €)
          example: 2614.79
          type: number
        interest:
          description: Amount of the interest accrued in € ( = anfallender Zinsbetrag
            in €)
          example: 234.56
          type: number
        totalValue:
          description: Amount of the total value in € ( = Gesamtsumme in €)
          example: 2849.35
          type: number
        decisionOutcome:
          description: Outcome of the credit decision
          enum:
          - POSITIVE
          - NEGATIVE
          example: POSITIVE
          type: string
        numberOfInstallments:
          description: Number of Installments defined in the payment plan ( = anzahl
            der Raten)
          example: 9
          type: integer
        installment:
          description: Amount in € of a single installment according to the payment
            plan ( = betrag der Rate in €)
          example: 302
          type: number
        lastInstallment:
          description: Amount  in € of the last installment according to the payment
            plan ( = betrag der letzten Rate in €)
          example: 293.58
          type: number
      type: object
    AuthorizationStatusResponse:
      properties:
        status:
          enum:
          - PREAUTHORIZED
          - PENDING
          - CANCELED
          type: string
      type: object
    ConstraintViolation:
      properties:
        title:
          type: string
        violations:
          items:
            $ref: '#/components/schemas/ConstraintViolation_violations'
          minItems: 1
          type: array
      required:
      - title
      - violations
      type: object
    ServerError:
      properties:
        title:
          type: string
        detail:
          type: string
      type: object
    AuthenticationError:
      properties:
        title:
          type: string
        detail:
          type: string
      type: object
    ShippingAddress_allOf:
      properties:
        firstName:
          description: Should match with the first name given in the person data
          type: string
        lastName:
          description: Should match with the last name given in the person data
          type: string
      required:
      - firstName
      - lastName
    ConstraintViolation_violations:
      properties:
        field:
          type: string
        message:
          type: string
      required:
      - field
      - message
  securitySchemes:
    basicAuth:
      description: username/password -> webshop id/ratenkauf token
      scheme: basic
      type: http
